spring:
  h2:
    console:
      enabled: true
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:~/test
#    username: sa
#    password:

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database: H2
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        query.in_clause_parameter_padding: true